# Generated by Django 6.0.3 on 2026-04-05 00:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morador',
            options={'ordering': ['nome'], 'verbose_name': 'Morador', 'verbose_name_plural': 'Moradores'},
        ),
        migrations.AlterModelOptions(
            name='republica',
            options={'ordering': ['nome'], 'verbose_name': 'Republica', 'verbose_name_plural': 'Republicas'},
        ),
        migrations.AddField(
            model_name='morador',
            name='data_entrada',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('ALUGUEL', 'Aluguel'), ('AGUA', 'Agua'), ('ENERGIA', 'Energia'), ('INTERNET', 'Internet'), ('MERCADO', 'Mercado'), ('LIMPEZA', 'Limpeza'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_despesa', models.DateField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('paga_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_pagas', to='core.morador')),
                ('republica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='core.republica')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_despesa', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DivisaoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_devido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quitado', models.BooleanField(default=False)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisoes', to='core.despesa')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisoes_despesa', to='core.morador')),
            ],
            options={
                'verbose_name': 'Divisao de despesa',
                'verbose_name_plural': 'Divisoes de despesa',
                'ordering': ['morador__nome'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('data_pagamento', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_realizados', to='core.morador')),
                ('recebedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_recebidos', to='core.morador')),
                ('referencia_despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='core.despesa')),
                ('republica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.republica')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluida')], default='PENDENTE', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('republica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.republica')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='core.morador')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['status', 'data_limite', 'titulo'],
            },
        ),
        migrations.AddConstraint(
            model_name='despesa',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gt', 0)), name='despesa_valor_total_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='divisaodespesa',
            constraint=models.UniqueConstraint(fields=('despesa', 'morador'), name='unique_divisao_por_morador'),
        ),
        migrations.AddConstraint(
            model_name='divisaodespesa',
            constraint=models.CheckConstraint(condition=models.Q(('valor_devido__gte', 0)), name='divisao_valor_devido_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='pagamento_valor_gt_zero'),
        ),
    ]
